### ISSUE TITLE
Add support for Polish translation

### ISSUE THREAD

**Issue by Chefski** [daywalk3r666/Kvaesitso-Icons#25]
### About this discussion

Could Polish be added to the translations?

**Comment by daywalk3r666** [comment]
Sure i can add polish to weblate

**Comment by daywalk3r666** [comment]
https://i18n.mm20.de/projects/kvaesitso-icons/strings/pl/

**Comment by Chefski** [comment]
Thank you <3

**Comment by Chefski** [comment]
Np :) done

**Comment by Chefski** [comment]
If you want I can also add translation for Czech and Slovak however some translations may be a little off. Might be a little off but its something :D

**Comment by daywalk3r666** [comment]
Done
